name: flutter_fft
description: Flutter plugin for my guitar tuner.
version: 0.0.1
author: slins<slins_23@hotmail.com>
homepage: https://github.com/slins-23/flutter-fft
environment:
    sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.slins.flutterfft
    pluginClass: FlutterFftPlugin
